# Generated by Django 4.0.3 on 2022-03-02 09:30

import apps.users.models.profiles
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('photo', models.ImageField(blank=True, upload_to=apps.users.models.profiles.get_avatar_place)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth ')),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('duty', models.CharField(choices=[('PA', 'Some Ptw Maker'), ('AA', 'Sahe Reisi'), ('OEE', 'Operation Engineer'), ('OIM', 'Reis'), ('Coordinator', 'Coordinator')], max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
